services:
  app:
    build:
      context: .
      target: builder # Use the builder stage for development
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app  # Mount local code into the container
    command: air # Run air for hot-reloading